
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fawzanpriatmana
 */
public class menuProgram extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuProgram.class.getName());

    /**
     * Creates new form menuProgram
     */
    public menuProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupStatusMember = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kotakNamaCust = new javax.swing.JTextField();
        radioNonMember = new javax.swing.JRadioButton();
        radioKosmikPlatinum = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listNamaProdukCust = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listHargaProdukCust = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        tombolProsesTransaksi = new javax.swing.JButton();
        tombolClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cekTakeaway = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        tombolInfo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listStruk = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kotakUangDiterima = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Program Kasir Kafe Kosmik");

        jLabel2.setText("Nama Customer: ");

        jLabel3.setText("Member Customer:");

        jLabel4.setText("Produk Pilihan: ");

        groupStatusMember.add(radioNonMember);
        radioNonMember.setSelected(true);
        radioNonMember.setText("Non Member");
        radioNonMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNonMemberActionPerformed(evt);
            }
        });

        groupStatusMember.add(radioKosmikPlatinum);
        radioKosmikPlatinum.setText("Kosmik Platinum");

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Iced Americano", "22000"},
                {"Hot Americano", "22000"},
                {"Iced Latte", "24000"},
                {"Iced Cappuccino", "29000"},
                {"Hot Cappuccino", "29000"},
                {"Hot Espresso", "19000"},
                {"Iced Caramel Macchiato", "25000"},
                {"Croissannt", "15000"},
                {"American Pancake", "24000"}
            },
            new String [] {
                "Nama Barang", "Harga Barang (Rp.)"
            }
        ));
        tabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelProduk);

        jScrollPane2.setViewportView(listNamaProdukCust);

        jScrollPane3.setViewportView(listHargaProdukCust);

        jLabel6.setText("Nama Produk");

        tombolProsesTransaksi.setText("Proses Transaksi");
        tombolProsesTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolProsesTransaksiActionPerformed(evt);
            }
        });

        tombolClear.setText("Clear");
        tombolClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolClearActionPerformed(evt);
            }
        });

        jLabel7.setText("Takeaway? :");

        cekTakeaway.setText("Takeaway");

        jLabel8.setText("Harga");

        tombolInfo.setText("Info");

        jScrollPane4.setViewportView(listStruk);

        jLabel5.setText("Struk");

        jLabel9.setText("Uang Diterima (Rp) : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cekTakeaway)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioNonMember)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioKosmikPlatinum))
                            .addComponent(kotakNamaCust, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(kotakUangDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombolClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tombolProsesTransaksi)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(688, 688, 688)
                        .addComponent(tombolInfo)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tombolInfo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kotakNamaCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(radioNonMember)
                            .addComponent(radioKosmikPlatinum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cekTakeaway))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(kotakUangDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tombolProsesTransaksi)
                                .addComponent(tombolClear)))))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioNonMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNonMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNonMemberActionPerformed

    private void tombolProsesTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolProsesTransaksiActionPerformed
        try {
            if (kotakNamaCust.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama Customer tidak boleh kosong :3");
            } else {
                strukListModel.removeAllElements();
                listStruk.setModel(strukListModel);
                String namaCust = kotakNamaCust.getText();
                String statusCust = "";
                if (radioNonMember.isSelected()) {
                    statusCust = "Non Member";
                } else if (radioKosmikPlatinum.isSelected()) {
                    statusCust = "Kosmik Platinum Member";
                }
                String statusMakan = "";
                if (cekTakeaway.isSelected()) {
                    statusMakan = "Takeaway";
                } else {
                    statusMakan = "Dine In";
                }
                int uangDiterima = Integer.parseInt(kotakUangDiterima.getText());
                strukListModel.addElement("--------------------------------------------------------------------");
                strukListModel.addElement("Nama Cust       :  " + namaCust);
                strukListModel.addElement("Status Cust       :  " + statusCust);
                strukListModel.addElement("Status Makan   :  " + statusMakan);
                strukListModel.addElement("--------------------------------------------------------------------");
                strukListModel.addElement("List Produk : ");
                int totalHarga = 0;
                if (listNamaProdukCustListModel.size() == listHargaProdukCustListModel.size()) {
                    for (int i = 0; i < listNamaProdukCustListModel.size(); i++) {
                        String namaProduk = (String) listNamaProdukCustListModel.getElementAt(i);
                        String hargaProduk = (String) listHargaProdukCustListModel.getElementAt(i);

                        strukListModel.addElement("--   " + namaProduk + "    (Rp. " + hargaProduk + ")");
                        totalHarga += Integer.parseInt(hargaProduk);
                    }
                }
                if (uangDiterima < totalHarga) {
                    JOptionPane.showMessageDialog(this, "Uang tidak boleh kurang dari total harga ya. Tidak boleh hutang :3");
                    strukListModel.removeAllElements();
                    listStruk.setModel(strukListModel);
                } else {
                    strukListModel.addElement("--------------------------------------------------------------------");
                    strukListModel.addElement("Total Harga       :  Rp. " + totalHarga);
                    strukListModel.addElement("Uang Diterima  :  Rp. " + uangDiterima);
                    strukListModel.addElement("--------------------------------------------------------------------");
                    int uangKembalian = uangDiterima - totalHarga;
                    strukListModel.addElement("Kembalian         :  Rp. " + uangKembalian);
                    strukListModel.addElement("--------------------------------------------------------------------");
                    listStruk.setModel(strukListModel);
                    kotakNamaCust.setText("");
                    kotakUangDiterima.setText("");
                    listNamaProdukCustListModel.removeAllElements();
                    listHargaProdukCustListModel.removeAllElements();
                    listNamaProdukCust.setModel(listNamaProdukCustListModel);
                    listHargaProdukCust.setModel(listHargaProdukCustListModel);
                    kotakNamaCust.requestFocusInWindow();
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ada masalah. Silahkan cek ulang lagi. Pastikan masukkan anda sudah benar!");
        }     
    }//GEN-LAST:event_tombolProsesTransaksiActionPerformed

    private void tabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProdukMouseClicked
        int barisTerpilih = tabelProduk.getSelectedRow();
        
        String namaProduk = tabelProduk.getValueAt(barisTerpilih, 0).toString();
        String hargaProduk = tabelProduk.getValueAt(barisTerpilih, 1).toString();
        
        listNamaProdukCustListModel.addElement(namaProduk);
        listHargaProdukCustListModel.addElement(hargaProduk);
        
        listNamaProdukCust.setModel(listNamaProdukCustListModel);
        listHargaProdukCust.setModel(listHargaProdukCustListModel);
    }//GEN-LAST:event_tabelProdukMouseClicked

    private void tombolClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolClearActionPerformed
        kotakNamaCust.setText("");
        kotakUangDiterima.setText("");
        radioNonMember.setSelected(true);
        cekTakeaway.setSelected(false);
        listNamaProdukCustListModel.removeAllElements();
        listHargaProdukCustListModel.removeAllElements();
        listNamaProdukCust.setModel(listNamaProdukCustListModel);
        listHargaProdukCust.setModel(listHargaProdukCustListModel);
        strukListModel.removeAllElements();
        listStruk.setModel(strukListModel);

        kotakNamaCust.requestFocusInWindow();
    }//GEN-LAST:event_tombolClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuProgram().setVisible(true));
    }

    DefaultListModel listNamaProdukCustListModel = new DefaultListModel();
    DefaultListModel listHargaProdukCustListModel = new DefaultListModel();
    DefaultListModel strukListModel = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cekTakeaway;
    private javax.swing.ButtonGroup groupStatusMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField kotakNamaCust;
    private javax.swing.JTextField kotakUangDiterima;
    private javax.swing.JList<String> listHargaProdukCust;
    private javax.swing.JList<String> listNamaProdukCust;
    private javax.swing.JList<String> listStruk;
    private javax.swing.JRadioButton radioKosmikPlatinum;
    private javax.swing.JRadioButton radioNonMember;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JButton tombolClear;
    private javax.swing.JButton tombolInfo;
    private javax.swing.JButton tombolProsesTransaksi;
    // End of variables declaration//GEN-END:variables
}
